name = "GeoTables"
uuid = "e502b557-6362-48c1-8219-d30d308dcdb0"
authors = ["Júlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "1.4.4"

[deps]
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Meshes = "0.34"
Tables = "1.10"
julia = "1.9"
